version: '3.5'
services: 
    madam.v2-db:
        image: mariadb:latest
        container_name: app-madam.v2-db
        environment: 
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
        restart: on-failure
        ports: 
            - '127.0.0.1:3306:3306'
        volumes: 
            - ./docker:/var/lib/mysql
        networks: 
            - madam.v2
    madam.v2:
        depends_on:
            - madam.v2-db
        build: .
        restart: unless-stopped
        volumes: 
            - ./:/var/www/html
        ports: 
            - '127.0.0.1:8080:80'
        networks: 
            - madam.v2
        environment: 
            - DB_SERVER=${DB_SERVER}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - CUSTOMER_TABLE=${CUSTOMER_TABLE}
            - USER_TABLE=${USER_TABLE}
            - CID_TABLE=${CID_TABLE}
networks: 
    madam.v2:
        name: madam.v2
        driver: bridge
